<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Sección 2 Regresión múltiple | Estadística Multivariada</title>
  <meta name="description" content="Curso ENES Morelia Semestre 2026-1" />
  <meta name="generator" content="bookdown 0.43 and GitBook 2.6.7" />

  <meta property="og:title" content="Sección 2 Regresión múltiple | Estadística Multivariada" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Curso ENES Morelia Semestre 2026-1" />
  <meta name="github-repo" content="HaydeePeruyero/MultivariateStatisticalAnalysis" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Sección 2 Regresión múltiple | Estadística Multivariada" />
  
  <meta name="twitter:description" content="Curso ENES Morelia Semestre 2026-1" />
  

<meta name="author" content="Haydeé Peruyero" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="análisis-de-componentes-principales.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">MultivariateStatisticalAnalysis</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="01-Regresion_multiple.html"><a href="#estad%C3%ADstica-multivariada"><i class="fa fa-check"></i><b>1</b> Estadística Multivariada</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1.1</b> Temario</a></li>
<li class="chapter" data-level="1.2" data-path="01-Regresion_multiple.html"><a href="#evaluaci%C3%B3n"><i class="fa fa-check"></i><b>1.2</b> Evaluación</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#proyecto-final"><i class="fa fa-check"></i><b>1.3</b> Proyecto final</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#referencias"><i class="fa fa-check"></i><b>1.4</b> Referencias</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#material-interesante"><i class="fa fa-check"></i><b>1.5</b> Material interesante</a></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#datacamp"><i class="fa fa-check"></i><b>1.6</b> DataCamp</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="01-Regresion_multiple.html"><a href="#regresi%C3%B3n-m%C3%BAltiple"><i class="fa fa-check"></i><b>2</b> Regresión múltiple</a>
<ul>
<li class="chapter" data-level="2.1" data-path="01-Regresion_multiple.html"><a href="#por-qu%C3%A9-estad%C3%ADstica-multivariada"><i class="fa fa-check"></i><b>2.1</b> ¿Por qué estadística multivariada?</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="01-Regresion_multiple.html"><a href="#qu%C3%A9-es-multivariado-y-por-qu%C3%A9-lo-necesitamos"><i class="fa fa-check"></i><b>2.1.1</b> ¿Qué es “multivariado” y por qué lo necesitamos?</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="01-Regresion_multiple.html"><a href="#regresi%C3%B3n-m%C3%BAltiple-1"><i class="fa fa-check"></i><b>2.2</b> Regresión múltiple</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="01-Regresion_multiple.html"><a href="#modelo-y-estimaci%C3%B3n"><i class="fa fa-check"></i><b>2.2.1</b> Modelo y estimación</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="01-Regresion_multiple.html"><a href="#estimaci%C3%B3n-de-par%C3%A1metros"><i class="fa fa-check"></i><b>2.3</b> Estimación de parámetros</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="regresión-múltiple.html"><a href="regresión-múltiple.html"><i class="fa fa-check"></i><b>2.3.1</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="01-Regresion_multiple.html"><a href="#pruebas-de-hip%C3%B3tesis"><i class="fa fa-check"></i><b>2.4</b> Pruebas de Hipótesis</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="01-Regresion_multiple.html"><a href="#prueba-de-la-significancia-de-la-regresi%C3%B3n"><i class="fa fa-check"></i><b>2.4.1</b> Prueba de la significancia de la regresión</a></li>
<li class="chapter" data-level="2.4.2" data-path="01-Regresion_multiple.html"><a href="#pruebas-sobre-coeficientes-individuales-de-regresi%C3%B3n"><i class="fa fa-check"></i><b>2.4.2</b> Pruebas sobre coeficientes individuales de regresión</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="regresión-múltiple.html"><a href="regresión-múltiple.html#intervalos-de-confianza"><i class="fa fa-check"></i><b>2.5</b> Intervalos de confianza</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="regresión-múltiple.html"><a href="regresión-múltiple.html#intervalo-de-confianza-de-la-respuesta-media"><i class="fa fa-check"></i><b>2.5.1</b> Intervalo de confianza de la respuesta media</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="01-Regresion_multiple.html"><a href="#an%C3%A1lisis-de-componentes-principales"><i class="fa fa-check"></i><b>3</b> Análisis de Componentes Principales</a></li>
<li class="chapter" data-level="4" data-path="01-Regresion_multiple.html"><a href="#an%C3%A1lisis-factorial"><i class="fa fa-check"></i><b>4</b> Análisis Factorial</a></li>
<li class="chapter" data-level="5" data-path="01-Regresion_multiple.html"><a href="#an%C3%A1lisis-de-conglomerados"><i class="fa fa-check"></i><b>5</b> Análisis de Conglomerados</a></li>
<li class="chapter" data-level="6" data-path="01-Regresion_multiple.html"><a href="#an%C3%A1lisis-de-discriminante"><i class="fa fa-check"></i><b>6</b> Análisis de Discriminante</a></li>
<li class="chapter" data-level="7" data-path="01-Regresion_multiple.html"><a href="#ap%C3%A9ndices"><i class="fa fa-check"></i><b>7</b> Apéndices</a>
<ul>
<li class="chapter" data-level="7.1" data-path="01-Regresion_multiple.html"><a href="#introducci%C3%B3n-a-r"><i class="fa fa-check"></i><b>7.1</b> Introducción a R</a></li>
<li class="chapter" data-level="7.2" data-path="apéndices.html"><a href="apéndices.html"><i class="fa fa-check"></i><b>7.2</b> Git + Github</a></li>
<li class="chapter" data-level="7.3" data-path="01-Regresion_multiple.html"><a href="#gr%C3%A1ficas-multivariadas"><i class="fa fa-check"></i><b>7.3</b> Gráficas Multivariadas</a></li>
<li class="chapter" data-level="7.4" data-path="01-Regresion_multiple.html"><a href="#escalas-de-medici%C3%B3n"><i class="fa fa-check"></i><b>7.4</b> Escalas de Medición</a></li>
<li class="chapter" data-level="7.5" data-path="apéndices.html"><a href="apéndices.html#valores-faltantes"><i class="fa fa-check"></i><b>7.5</b> Valores Faltantes</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/HaydeePeruyero/MultivariateStatisticalAnalysis/" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Estadística Multivariada</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="regresión-múltiple" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">Sección 2</span> Regresión múltiple<a href="#regresi%C3%B3n-m%C3%BAltiple" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="por-qué-estadística-multivariada" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> ¿Por qué estadística multivariada?<a href="#por-qu%C3%A9-estad%C3%ADstica-multivariada" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>El proceso de modelado consiste en construir expresiones matemáticas que permitan representar el comportamiento de una variable que queremos estudiar. Cuando contamos con varias variables, suele interesarnos analizar cómo unas influyen sobre otras, determinando si existe una relación, su intensidad y su forma. En muchos casos, estas relaciones pueden ser complejas y difíciles de describir directamente; por ello, se busca aproximarlas mediante funciones matemáticas sencillas como polinomios, que conserven los elementos esenciales para explicar el fenómeno de interés.</p>
<p>Cuando estudiamos fenómenos deterministas, es común vincular una variable dependiente con una o más variables independientes. Por ejemplo, en la ecuación de la velocidad (<span class="math inline">\(v=d/t\)</span>), la distancia depende de la velocidad y del tiempo. En la práctica, cuando realizamos distintos experimentos, las fórmulas deterministas podrían no capturar por completo el comportamiento observado. Esto puede deberse a factores no controlados, a la presencia de variabilidad natural o a efectos aleatorios. Por esta razón, además de la parte determinista del modelo, se incorpora un término que represente la discrepancia aleatoria entre lo que se predice y lo que efectivamente se observa. De forma general, esta idea se resume como:</p>
<p><span class="math display">\[Observación = Modelo \ + \ Error\]</span></p>
<p>Cuando se supone que la relación entre las variables puede representarse mediante una ecuación lineal, hablamos de <em>análisis de regresión lineal</em>. Si intervienen únicamente dos variables, una dependiente <span class="math inline">\(y\)</span> y independiente <span class="math inline">\(x\)</span>, se trata de <strong>regresión lineal simple</strong>. En cambio, cuando la variable de interés <span class="math inline">\(y\)</span> depende de dos o más variables independientes <span class="math inline">\(x_1,x_2, ...\)</span> hablamos de <strong>regresión lineal múltiple</strong>.</p>
<p><em>Supongamos que queremos predecir el rendimiento académico de un estudiante, ¿solo necesitamos las horas que estudia?</em></p>
<p>En este caso se tiene que el puntaje o rendimiento lo podemos representar con <span class="math inline">\(y\)</span> y las horas de estudio con <span class="math inline">\(x\)</span>. Entonces esta propuesta de modelo, la podríamos representar como:</p>
<p><span class="math display">\[y=\beta_0+\beta_1x\]</span>
Donde <span class="math inline">\(\beta_0\)</span> es la ordenada al origen y <span class="math inline">\(\beta_1\)</span> la pendiente. Esta recta podría no ajustarse al modelo por diferentes razones, entonces lo que se hace es considerar un error aleatorio <span class="math inline">\(\epsilon\)</span>. El modelo que ya considera este error se representa como:</p>
<p><span class="math display">\[y=\beta_0+\beta_1x+\epsilon.\]</span></p>
<p>A este modelo se le conoce como modelo de <strong>regresión lineal simple</strong> y a <span class="math inline">\(\beta_0,\beta_1\)</span> se les conoce como <strong>coeficientes de regresión</strong>.</p>
<p>En problemas reales, casi nunca una sola variable explica el fenómeno. Las decisiones y predicciones mejoran cuando integramos múltiples fuentes de información.</p>
<p>Ejemplos:
- Salud: riesgo de una enfermedad según edad, IMC, actividad física, dieta y antecedentes.
- Ingeniería: vida útil de una pieza según temperatura, vibración, material y carga.
- Biología: crecimiento de una planta por agua, luz, fertilizante, temperatura.</p>
<p><strong>Ejemplo:</strong> Si queremos predecir el rendimiento académico de un estudiante, ¿solo necesitamos las horas que estudia? ¿qué otras variables podrían influir en el puntaje de un examen?</p>
<details>
<summary>
<b> Rendimiento escolar </b>
</summary>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="regresión-múltiple.html#cb1-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb1-2"><a href="regresión-múltiple.html#cb1-2" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb1-3"><a href="regresión-múltiple.html#cb1-3" tabindex="-1"></a>data_intro <span class="ot">&lt;-</span> <span class="fu">tibble</span>(</span>
<span id="cb1-4"><a href="regresión-múltiple.html#cb1-4" tabindex="-1"></a>  <span class="at">estudiante =</span> <span class="fu">paste0</span>(<span class="st">&quot;E&quot;</span>, <span class="dv">1</span><span class="sc">:</span>n),</span>
<span id="cb1-5"><a href="regresión-múltiple.html#cb1-5" tabindex="-1"></a>  <span class="at">horas_estudio =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>),</span>
<span id="cb1-6"><a href="regresión-múltiple.html#cb1-6" tabindex="-1"></a>  <span class="at">horas_sueno  =</span> <span class="fu">c</span>(<span class="dv">7</span>,<span class="dv">8</span>,<span class="dv">6</span>,<span class="dv">7</span>,<span class="dv">5</span>,<span class="dv">8</span>,<span class="dv">7</span>,<span class="dv">6</span>,<span class="dv">9</span>,<span class="dv">7</span>),</span>
<span id="cb1-7"><a href="regresión-múltiple.html#cb1-7" tabindex="-1"></a>  <span class="at">asistencia   =</span> <span class="fu">c</span>(<span class="fl">0.9</span>,<span class="fl">0.95</span>,<span class="fl">0.8</span>,<span class="fl">0.85</span>,<span class="fl">0.7</span>,<span class="fl">0.9</span>,<span class="fl">0.8</span>,<span class="fl">0.9</span>,<span class="dv">1</span>,<span class="fl">0.95</span>),</span>
<span id="cb1-8"><a href="regresión-múltiple.html#cb1-8" tabindex="-1"></a>  <span class="at">puntaje      =</span> <span class="fu">c</span>(<span class="dv">65</span>,<span class="dv">70</span>,<span class="dv">68</span>,<span class="dv">80</span>,<span class="dv">60</span>,<span class="dv">75</span>,<span class="dv">65</span>,<span class="dv">78</span>,<span class="dv">88</span>,<span class="dv">85</span>)</span>
<span id="cb1-9"><a href="regresión-múltiple.html#cb1-9" tabindex="-1"></a>)</span>
<span id="cb1-10"><a href="regresión-múltiple.html#cb1-10" tabindex="-1"></a>data_intro</span></code></pre></div>
<pre><code>## # A tibble: 10 × 5
##    estudiante horas_estudio horas_sueno asistencia puntaje
##    &lt;chr&gt;              &lt;dbl&gt;       &lt;dbl&gt;      &lt;dbl&gt;   &lt;dbl&gt;
##  1 E1                     2           7       0.9       65
##  2 E2                     3           8       0.95      70
##  3 E3                     4           6       0.8       68
##  4 E4                     5           7       0.85      80
##  5 E5                     1           5       0.7       60
##  6 E6                     3           8       0.9       75
##  7 E7                     2           7       0.8       65
##  8 E8                     4           6       0.9       78
##  9 E9                     5           9       1         88
## 10 E10                    6           7       0.95      85</code></pre>
</details>
<p>¿Qué pasa si solo graficamos horas de estudio vs puntaje?</p>
<details>
<summary>
<b> Plot hotas de estudio vs puntaje sugerida</b>
</summary>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="regresión-múltiple.html#cb3-1" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb3-2"><a href="regresión-múltiple.html#cb3-2" tabindex="-1"></a><span class="fu">ggplot</span>(data_intro, <span class="fu">aes</span>(horas_estudio, puntaje)) <span class="sc">+</span></span>
<span id="cb3-3"><a href="regresión-múltiple.html#cb3-3" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size=</span><span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb3-4"><a href="regresión-múltiple.html#cb3-4" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method=</span><span class="st">&quot;lm&quot;</span>, <span class="at">se=</span><span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb3-5"><a href="regresión-múltiple.html#cb3-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">&quot;¿Solo horas de estudio explican el puntaje?&quot;</span>)</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="MultivariateStatisticalAnalysis_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
</details>
<p>¿Se ajusta un modelo lineal? ¿Porqué?</p>
<div id="qué-es-multivariado-y-por-qué-lo-necesitamos" class="section level3 hasAnchor" number="2.1.1">
<h3><span class="header-section-number">2.1.1</span> ¿Qué es “multivariado” y por qué lo necesitamos?<a href="#qu%C3%A9-es-multivariado-y-por-qu%C3%A9-lo-necesitamos" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>Idea central:</strong> cuando <strong>varias</strong> <span class="math inline">\(x\)</span> influyen sobre <span class="math inline">\(y\)</span>, estudiar cada <span class="math inline">\(x\)</span> por separado puede engañarnos. El análisis multivariado permite:</p>
<ul>
<li><strong>Aislar efectos</strong>: estimar el efecto de <span class="math inline">\(x_1\)</span> <em>manteniendo constantes</em> <span class="math inline">\(x_2,x_3,...\)</span>.</li>
<li><strong>Mejorar predicción</strong>: reducir error al añadir información relevante.</li>
<li><strong>Controlar confusores</strong>: variables que cambian la relación aparente entre <span class="math inline">\(y\)</span> y <span class="math inline">\(x\)</span>.</li>
</ul>
<p><strong>Ejemplo:</strong> Si ajustamos ahora un modelo con varias variables, ¿vamos a observar un cambio? ¿se ajustará mejor?</p>
<details>
<summary>
<b>Código (modelos + comparaciones)</b>
</summary>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="regresión-múltiple.html#cb5-1" tabindex="-1"></a><span class="co"># Modelo simple</span></span>
<span id="cb5-2"><a href="regresión-múltiple.html#cb5-2" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(puntaje <span class="sc">~</span> horas_estudio, <span class="at">data =</span> data_intro)</span>
<span id="cb5-3"><a href="regresión-múltiple.html#cb5-3" tabindex="-1"></a></span>
<span id="cb5-4"><a href="regresión-múltiple.html#cb5-4" tabindex="-1"></a><span class="co"># Modelo múltiple</span></span>
<span id="cb5-5"><a href="regresión-múltiple.html#cb5-5" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(puntaje <span class="sc">~</span> horas_estudio <span class="sc">+</span> horas_sueno <span class="sc">+</span> asistencia, <span class="at">data =</span> data_intro)</span>
<span id="cb5-6"><a href="regresión-múltiple.html#cb5-6" tabindex="-1"></a></span>
<span id="cb5-7"><a href="regresión-múltiple.html#cb5-7" tabindex="-1"></a><span class="co"># Medidas clave</span></span>
<span id="cb5-8"><a href="regresión-múltiple.html#cb5-8" tabindex="-1"></a>R2_m1  <span class="ot">&lt;-</span> <span class="fu">glance</span>(m1)<span class="sc">$</span>r.squared</span>
<span id="cb5-9"><a href="regresión-múltiple.html#cb5-9" tabindex="-1"></a>R2_m2  <span class="ot">&lt;-</span> <span class="fu">glance</span>(m2)<span class="sc">$</span>r.squared</span>
<span id="cb5-10"><a href="regresión-múltiple.html#cb5-10" tabindex="-1"></a></span>
<span id="cb5-11"><a href="regresión-múltiple.html#cb5-11" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">&quot;El R2 del modelo simple:&quot;</span>, R2_m1))</span></code></pre></div>
<pre><code>## [1] &quot;El R2 del modelo simple: 0.824317362184441&quot;</code></pre>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="regresión-múltiple.html#cb7-1" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(<span class="st">&quot;El R2 del modelo multiple:&quot;</span>, R2_m2))</span></code></pre></div>
<pre><code>## [1] &quot;El R2 del modelo multiple: 0.895428180549875&quot;</code></pre>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="regresión-múltiple.html#cb9-1" tabindex="-1"></a><span class="co">#R2adj_m1 &lt;- glance(m1)$adj.r.squared</span></span>
<span id="cb9-2"><a href="regresión-múltiple.html#cb9-2" tabindex="-1"></a><span class="co">#R2adj _m2 &lt;- glance(m2)$adj.r.squared</span></span></code></pre></div>
<ul>
<li>¿Aumentó <span class="math inline">\(R^2\)</span> al incluir más variables? ¿Por qué tiende a subir?</li>
<li>¿Qué cambia en la interpretación de horas_estudio al controlar por horas_sueno y asistencia?</li>
<li>¿Puede un predictor ser importante en bivariado y no en multivariado (o viceversa)?</li>
</ul>
</div>
</div>
<div id="regresión-múltiple-1" class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Regresión múltiple<a href="#regresi%C3%B3n-m%C3%BAltiple-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="modelo-y-estimación" class="section level3 hasAnchor" number="2.2.1">
<h3><span class="header-section-number">2.2.1</span> Modelo y estimación<a href="#modelo-y-estimaci%C3%B3n" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Los modelos en regresión lineal múltiple están dados por la siguiente forma, donde <span class="math inline">\(y\)</span> depende de <span class="math inline">\(p\)</span> variables predictoras:</p>
<p><span class="math display">\[y_i=\beta_0+\beta_1x_{i1}+\beta_2x_{i2} + \beta_px_{ip}+\epsilon_i.\]</span></p>
<p>Se suele asumir que los errores <span class="math inline">\(\epsilon_i\)</span> son i.i.d. con distribución normal de media 0 y varianza <span class="math inline">\(\sigma^2\)</span> desconocida. Los coeficientes <span class="math inline">\(\beta_i\)</span> son constantes desconocidas y son los parámetros del modelo. Cada <span class="math inline">\(\beta_j\)</span> representa el cambio esperado en la respuesta <span class="math inline">\(y\)</span> por el cambio unitario en <span class="math inline">\(x_i\)</span> cuando todas las demás variables independientes <span class="math inline">\(x_i(i\neq j)\)</span> se mantienen constantes.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="regresión-múltiple.html#cb10-1" tabindex="-1"></a><span class="co"># Forma general</span></span>
<span id="cb10-2"><a href="regresión-múltiple.html#cb10-2" tabindex="-1"></a>ajuste <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x1 <span class="sc">+</span> x2 <span class="sc">+</span> ... <span class="sc">+</span> xp, <span class="at">data =</span> datos)</span>
<span id="cb10-3"><a href="regresión-múltiple.html#cb10-3" tabindex="-1"></a><span class="co"># summary(ajuste)</span></span></code></pre></div>
<p>Los coeficientes los podemos interpretar como sigue:</p>
<ul>
<li><strong>Intercepto (<span class="math inline">\(\beta_0\)</span>)</strong>: valor esperado de <span class="math inline">\(y\)</span> cuando todas las <span class="math inline">\(x\)</span>=0.</li>
<li><strong>Pendiente <span class="math inline">\(\beta_j\)</span></strong>: efecto <strong>parcial</strong> de <span class="math inline">\(x_j\)</span> sobre <span class="math inline">\(y\)</span> manteniendo las demás constantes.</li>
</ul>
<p>En los modelos de regreción lineal, solemos usar las siguientes medidas de bondad de ajuste:</p>
<ul>
<li><strong><span class="math inline">\(R^2\)</span></strong>: proporción de varianza de <span class="math inline">\(y\)</span> explicada.</li>
<li><strong><span class="math inline">\(R^2\)</span> ajustado</strong>: penaliza por número de predictores (mejor para comparar modelos con distinto número de x).</li>
<li><strong>RMSE (<span class="math inline">\(\sigma\)</span>)</strong>: error típico de predicción en unidades de <span class="math inline">\(y\)</span>.</li>
</ul>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="regresión-múltiple.html#cb11-1" tabindex="-1"></a>comp <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">bind_rows</span>(</span>
<span id="cb11-2"><a href="regresión-múltiple.html#cb11-2" tabindex="-1"></a>  <span class="fu">glance</span>(m1) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">modelo=</span><span class="st">&quot;simple&quot;</span>),</span>
<span id="cb11-3"><a href="regresión-múltiple.html#cb11-3" tabindex="-1"></a>  <span class="fu">glance</span>(m2) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">modelo=</span><span class="st">&quot;multiple&quot;</span>)</span>
<span id="cb11-4"><a href="regresión-múltiple.html#cb11-4" tabindex="-1"></a>) <span class="sc">%&gt;%</span> <span class="fu">select</span>(modelo, r.squared, adj.r.squared)</span>
<span id="cb11-5"><a href="regresión-múltiple.html#cb11-5" tabindex="-1"></a>comp</span></code></pre></div>
<pre><code>## # A tibble: 2 × 3
##   modelo   r.squared adj.r.squared
##   &lt;chr&gt;        &lt;dbl&gt;         &lt;dbl&gt;
## 1 simple       0.824         0.802
## 2 multiple     0.895         0.843</code></pre>
<p>Para este modelo algunos de los supuestos se siguen del modelo de regresión lineal
simple y se agregan algunos que tienen que ver con la relación que pudiera existir entre
las variables regresoras.</p>
<ul>
<li>El modelo es lineal en los parámetros.<br />
<em>Chequeo</em>: residuales vs ajustados sin patrón claro.</li>
<li>El modelo está especificado correctamente.</li>
<li>Covarianza cero entre variables regresoras y el error.</li>
<li>Esperanza del error igual a cero.</li>
<li>Homocedasticidad.</li>
<li>No autocorrelación entre los errores.</li>
<li>Los errores siguen una distribución normal.</li>
<li>Mas observaciones que parámetros a estimar.</li>
<li>Variación entre los valores de las variables regresoras.</li>
<li>No colinealidad (multicolinealidad) entre las variables regresoras, es decir, no existe
una relación lineal entre <span class="math inline">\(x_i\)</span> y <span class="math inline">\(x_j\)</span> (es decir, las variables son linealmente independientes).</li>
</ul>
<details>
<summary>
<b>Supuestos</b>
</summary>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="regresión-múltiple.html#cb13-1" tabindex="-1"></a><span class="co"># Modelo m2</span></span>
<span id="cb13-2"><a href="regresión-múltiple.html#cb13-2" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb13-3"><a href="regresión-múltiple.html#cb13-3" tabindex="-1"></a><span class="fu">plot</span>(m2, <span class="at">which=</span><span class="dv">1</span>)  <span class="co"># Residuales vs ajustados</span></span>
<span id="cb13-4"><a href="regresión-múltiple.html#cb13-4" tabindex="-1"></a><span class="fu">plot</span>(m2, <span class="at">which=</span><span class="dv">2</span>)  <span class="co"># QQ-plot</span></span></code></pre></div>
<p><img src="MultivariateStatisticalAnalysis_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
</details>
<hr />
<p><strong>Ejercicio</strong>: Supongamos que tenemos los siguientes datos: precio de vivienda según metros, habitaciones y distancia al centro.</p>
<details>
<summary>
<b>Dataset</b>
</summary>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="regresión-múltiple.html#cb14-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb14-2"><a href="regresión-múltiple.html#cb14-2" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">14</span></span>
<span id="cb14-3"><a href="regresión-múltiple.html#cb14-3" tabindex="-1"></a>casas <span class="ot">&lt;-</span> tibble<span class="sc">::</span><span class="fu">tibble</span>(</span>
<span id="cb14-4"><a href="regresión-múltiple.html#cb14-4" tabindex="-1"></a>  <span class="at">precio =</span> <span class="fu">c</span>(<span class="dv">200</span>,<span class="dv">220</span>,<span class="dv">250</span>,<span class="dv">275</span>,<span class="dv">300</span>,<span class="dv">180</span>,<span class="dv">210</span>,<span class="dv">260</span>,<span class="dv">280</span>,<span class="dv">320</span>,<span class="dv">190</span>,<span class="dv">240</span>,<span class="dv">230</span>,<span class="dv">305</span>),</span>
<span id="cb14-5"><a href="regresión-múltiple.html#cb14-5" tabindex="-1"></a>  <span class="at">metros =</span> <span class="fu">c</span>(<span class="dv">80</span>,<span class="dv">90</span>,<span class="dv">100</span>,<span class="dv">110</span>,<span class="dv">120</span>,<span class="dv">70</span>,<span class="dv">85</span>,<span class="dv">105</span>,<span class="dv">115</span>,<span class="dv">130</span>,<span class="dv">75</span>,<span class="dv">95</span>,<span class="dv">92</span>,<span class="dv">125</span>),</span>
<span id="cb14-6"><a href="regresión-múltiple.html#cb14-6" tabindex="-1"></a>  <span class="at">habitaciones =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">4</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">3</span>,<span class="dv">4</span>),</span>
<span id="cb14-7"><a href="regresión-múltiple.html#cb14-7" tabindex="-1"></a>  <span class="at">distancia_centro =</span> <span class="fu">c</span>(<span class="dv">5</span>,<span class="dv">4</span>,<span class="dv">6</span>,<span class="dv">3</span>,<span class="dv">2</span>,<span class="dv">8</span>,<span class="dv">6</span>,<span class="dv">3</span>,<span class="dv">2</span>,<span class="dv">1</span>,<span class="dv">7</span>,<span class="dv">5</span>,<span class="dv">4</span>,<span class="dv">2</span>)</span>
<span id="cb14-8"><a href="regresión-múltiple.html#cb14-8" tabindex="-1"></a>)</span>
<span id="cb14-9"><a href="regresión-múltiple.html#cb14-9" tabindex="-1"></a>casas</span></code></pre></div>
<pre><code>## # A tibble: 14 × 4
##    precio metros habitaciones distancia_centro
##     &lt;dbl&gt;  &lt;dbl&gt;        &lt;dbl&gt;            &lt;dbl&gt;
##  1    200     80            2                5
##  2    220     90            3                4
##  3    250    100            3                6
##  4    275    110            4                3
##  5    300    120            4                2
##  6    180     70            2                8
##  7    210     85            3                6
##  8    260    105            3                3
##  9    280    115            4                2
## 10    320    130            5                1
## 11    190     75            2                7
## 12    240     95            3                5
## 13    230     92            3                4
## 14    305    125            4                2</code></pre>
</details>
<ol style="list-style-type: decimal">
<li>Ajusta <code>precio ~ metros</code> (simple) y <code>precio ~ metros + habitaciones + distancia_centro</code> (múltiple).<br />
</li>
<li>Compara <span class="math inline">\(R^2\)</span>, <span class="math inline">\(R^2\)</span> <strong>ajustado</strong> y <strong>σ (RMSE)</strong>.<br />
</li>
<li>Interpreta el coeficiente de <code>distancia_centro</code>.<br />
</li>
<li>Revisa QQ-plot y residuales vs ajustados. ¿Algún patrón?</li>
</ol>
<details>
<summary>
<b>Solución</b>
</summary>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="regresión-múltiple.html#cb16-1" tabindex="-1"></a>m_s <span class="ot">&lt;-</span> <span class="fu">lm</span>(precio <span class="sc">~</span> metros, <span class="at">data=</span>casas)</span>
<span id="cb16-2"><a href="regresión-múltiple.html#cb16-2" tabindex="-1"></a>m_m <span class="ot">&lt;-</span> <span class="fu">lm</span>(precio <span class="sc">~</span> metros <span class="sc">+</span> habitaciones <span class="sc">+</span> distancia_centro, <span class="at">data=</span>casas)</span>
<span id="cb16-3"><a href="regresión-múltiple.html#cb16-3" tabindex="-1"></a></span>
<span id="cb16-4"><a href="regresión-múltiple.html#cb16-4" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">glance</span>(m_s)[,<span class="fu">c</span>(<span class="st">&quot;r.squared&quot;</span>,<span class="st">&quot;adj.r.squared&quot;</span>)]</span></code></pre></div>
<pre><code>## # A tibble: 1 × 2
##   r.squared adj.r.squared
##       &lt;dbl&gt;         &lt;dbl&gt;
## 1     0.996         0.996</code></pre>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="regresión-múltiple.html#cb18-1" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">glance</span>(m_m)[,<span class="fu">c</span>(<span class="st">&quot;r.squared&quot;</span>,<span class="st">&quot;adj.r.squared&quot;</span>)]</span></code></pre></div>
<pre><code>## # A tibble: 1 × 2
##   r.squared adj.r.squared
##       &lt;dbl&gt;         &lt;dbl&gt;
## 1     0.997         0.996</code></pre>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="regresión-múltiple.html#cb20-1" tabindex="-1"></a>broom<span class="sc">::</span><span class="fu">tidy</span>(m_m)</span></code></pre></div>
<pre><code>## # A tibble: 4 × 5
##   term             estimate std.error statistic      p.value
##   &lt;chr&gt;               &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;        &lt;dbl&gt;
## 1 (Intercept)        -8.67     14.9      -0.583 0.573       
## 2 metros              2.53      0.162    15.6   0.0000000236
## 3 habitaciones       -0.505     2.80     -0.180 0.861       
## 4 distancia_centro    1.38      0.974     1.42  0.187</code></pre>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="regresión-múltiple.html#cb22-1" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb22-2"><a href="regresión-múltiple.html#cb22-2" tabindex="-1"></a><span class="fu">plot</span>(m_m, <span class="at">which=</span><span class="dv">1</span>)</span>
<span id="cb22-3"><a href="regresión-múltiple.html#cb22-3" tabindex="-1"></a><span class="fu">plot</span>(m_m, <span class="at">which=</span><span class="dv">2</span>)</span></code></pre></div>
<p><img src="MultivariateStatisticalAnalysis_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
</details>
</div>
</div>
<div id="estimación-de-parámetros" class="section level2 hasAnchor" number="2.3">
<h2><span class="header-section-number">2.3</span> Estimación de parámetros<a href="#estimaci%C3%B3n-de-par%C3%A1metros" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>Ejemplo (Montgomery, 2002):</strong> : Un embotellador de bebidas gaseosas analiza las rutas de servicio de las máquinas expendedoras en su sistema de distribución. Le interesa predecir el tiempo necesario para que el representante de ruta atienda las máquinas expendedoras en una tienda.</p>
<p>Esta actividad de servicio consiste en abastecer la máquina con productos embotellados, y algo de mantenimiento o limpieza. El ingeniero industrial responsable del estudio ha sugerido que las dos variables más importantes que afectan el tiempo de entrega <span class="math inline">\(y\)</span> son la cantidad de cajas de producto abastecido, <span class="math inline">\(x_1\)</span>, y la distancia caminada por el representante, <span class="math inline">\(x_2\)</span>.</p>
<p>El ingeniero ha reunido 25 observaciones de tiempo de entrega que se ven en la tabla siguiente. Se ajustará el modelo de regresión lineal multiple siguiente:</p>
<p><span class="math display">\[
y = \beta_0 + \beta_1 x_1 + \beta_2 x_2 +  \varepsilon
\]</span></p>
<p><em>Archivo: <code>refrescos.csv</code></em>.</p>
<details>
<summary>
<b>Base de datos</b>
</summary>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="regresión-múltiple.html#cb23-1" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb23-2"><a href="regresión-múltiple.html#cb23-2" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb23-3"><a href="regresión-múltiple.html#cb23-3" tabindex="-1"></a>  <span class="at">Observacion =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">25</span>,</span>
<span id="cb23-4"><a href="regresión-múltiple.html#cb23-4" tabindex="-1"></a>  <span class="at">y =</span> <span class="fu">c</span>(<span class="fl">16.68</span>, <span class="fl">11.50</span>, <span class="fl">12.03</span>, <span class="fl">14.88</span>, <span class="fl">13.75</span>,</span>
<span id="cb23-5"><a href="regresión-múltiple.html#cb23-5" tabindex="-1"></a>        <span class="fl">18.11</span>, <span class="fl">8.00</span>, <span class="fl">17.83</span>, <span class="fl">79.24</span>, <span class="fl">21.50</span>,</span>
<span id="cb23-6"><a href="regresión-múltiple.html#cb23-6" tabindex="-1"></a>        <span class="fl">40.33</span>, <span class="fl">21.00</span>, <span class="fl">13.50</span>, <span class="fl">19.75</span>, <span class="fl">24.00</span>,</span>
<span id="cb23-7"><a href="regresión-múltiple.html#cb23-7" tabindex="-1"></a>        <span class="fl">29.00</span>, <span class="fl">15.35</span>, <span class="fl">19.00</span>, <span class="fl">9.50</span>, <span class="fl">35.10</span>,</span>
<span id="cb23-8"><a href="regresión-múltiple.html#cb23-8" tabindex="-1"></a>        <span class="fl">17.90</span>, <span class="fl">52.32</span>, <span class="fl">18.75</span>, <span class="fl">19.83</span>, <span class="fl">10.75</span>),</span>
<span id="cb23-9"><a href="regresión-múltiple.html#cb23-9" tabindex="-1"></a>  <span class="at">x1 =</span> <span class="fu">c</span>(<span class="dv">7</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">6</span>,</span>
<span id="cb23-10"><a href="regresión-múltiple.html#cb23-10" tabindex="-1"></a>         <span class="dv">7</span>, <span class="dv">2</span>, <span class="dv">7</span>, <span class="dv">30</span>, <span class="dv">5</span>,</span>
<span id="cb23-11"><a href="regresión-múltiple.html#cb23-11" tabindex="-1"></a>         <span class="dv">16</span>, <span class="dv">10</span>, <span class="dv">4</span>, <span class="dv">6</span>, <span class="dv">9</span>,</span>
<span id="cb23-12"><a href="regresión-múltiple.html#cb23-12" tabindex="-1"></a>         <span class="dv">10</span>, <span class="dv">6</span>, <span class="dv">7</span>, <span class="dv">3</span>, <span class="dv">17</span>,</span>
<span id="cb23-13"><a href="regresión-múltiple.html#cb23-13" tabindex="-1"></a>         <span class="dv">10</span>, <span class="dv">26</span>, <span class="dv">9</span>, <span class="dv">8</span>, <span class="dv">4</span>),</span>
<span id="cb23-14"><a href="regresión-múltiple.html#cb23-14" tabindex="-1"></a>  <span class="at">x2 =</span> <span class="fu">c</span>(<span class="dv">560</span>, <span class="dv">220</span>, <span class="dv">340</span>, <span class="dv">80</span>, <span class="dv">150</span>,</span>
<span id="cb23-15"><a href="regresión-múltiple.html#cb23-15" tabindex="-1"></a>         <span class="dv">330</span>, <span class="dv">110</span>, <span class="dv">210</span>, <span class="dv">1460</span>, <span class="dv">605</span>,</span>
<span id="cb23-16"><a href="regresión-múltiple.html#cb23-16" tabindex="-1"></a>         <span class="dv">688</span>, <span class="dv">215</span>, <span class="dv">255</span>, <span class="dv">462</span>, <span class="dv">448</span>,</span>
<span id="cb23-17"><a href="regresión-múltiple.html#cb23-17" tabindex="-1"></a>         <span class="dv">776</span>, <span class="dv">200</span>, <span class="dv">132</span>, <span class="dv">36</span>, <span class="dv">770</span>,</span>
<span id="cb23-18"><a href="regresión-múltiple.html#cb23-18" tabindex="-1"></a>         <span class="dv">140</span>, <span class="dv">810</span>, <span class="dv">450</span>, <span class="dv">635</span>, <span class="dv">150</span>)</span>
<span id="cb23-19"><a href="regresión-múltiple.html#cb23-19" tabindex="-1"></a>)</span>
<span id="cb23-20"><a href="regresión-múltiple.html#cb23-20" tabindex="-1"></a></span>
<span id="cb23-21"><a href="regresión-múltiple.html#cb23-21" tabindex="-1"></a>datos</span></code></pre></div>
<pre><code>##    Observacion     y x1   x2
## 1            1 16.68  7  560
## 2            2 11.50  3  220
## 3            3 12.03  3  340
## 4            4 14.88  4   80
## 5            5 13.75  6  150
## 6            6 18.11  7  330
## 7            7  8.00  2  110
## 8            8 17.83  7  210
## 9            9 79.24 30 1460
## 10          10 21.50  5  605
## 11          11 40.33 16  688
## 12          12 21.00 10  215
## 13          13 13.50  4  255
## 14          14 19.75  6  462
## 15          15 24.00  9  448
## 16          16 29.00 10  776
## 17          17 15.35  6  200
## 18          18 19.00  7  132
## 19          19  9.50  3   36
## 20          20 35.10 17  770
## 21          21 17.90 10  140
## 22          22 52.32 26  810
## 23          23 18.75  9  450
## 24          24 19.83  8  635
## 25          25 10.75  4  150</code></pre>
</details>
<p>Veamos un gráfico de dispersión de los datos. ¿Qué observamos?</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="regresión-múltiple.html#cb25-1" tabindex="-1"></a><span class="fu">pairs</span>(datos[<span class="sc">-</span><span class="dv">1</span>])</span></code></pre></div>
<p><img src="MultivariateStatisticalAnalysis_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<ol style="list-style-type: decimal">
<li>Estimar <span class="math inline">\(\beta\)</span></li>
</ol>
<p>Primero, vamos a crear la matriz <span class="math inline">\(X\)</span> y el vector <span class="math inline">\(y\)</span>.</p>
<details>
<summary>
<b>Matrices</b>
</summary>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="regresión-múltiple.html#cb26-1" tabindex="-1"></a><span class="co"># Columna de 1 para el intercepto</span></span>
<span id="cb26-2"><a href="regresión-múltiple.html#cb26-2" tabindex="-1"></a>idv <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">1</span>, <span class="fu">nrow</span>(datos))</span>
<span id="cb26-3"><a href="regresión-múltiple.html#cb26-3" tabindex="-1"></a><span class="co"># Creamos matriz X</span></span>
<span id="cb26-4"><a href="regresión-múltiple.html#cb26-4" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(idv,datos<span class="sc">$</span>x1,datos<span class="sc">$</span>x2),<span class="at">nrow=</span><span class="dv">25</span>,<span class="at">ncol=</span><span class="dv">3</span>)</span>
<span id="cb26-5"><a href="regresión-múltiple.html#cb26-5" tabindex="-1"></a><span class="co"># Creamos el vector y</span></span>
<span id="cb26-6"><a href="regresión-múltiple.html#cb26-6" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">matrix</span>(datos<span class="sc">$</span>y, <span class="at">nrow =</span> <span class="dv">25</span>, <span class="at">ncol =</span> <span class="dv">1</span>)</span></code></pre></div>
</details>
<p>Ya sabemos que nuestro estimador está dado por</p>
<p><span class="math display">\[
\hat{\beta} = (X&#39;X)^{-1}X&#39;y
\]</span></p>
<p>Entonces podemos encontrar el estimador.</p>
<details>
<summary>
<b>Estimador beta</b>
</summary>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="regresión-múltiple.html#cb27-1" tabindex="-1"></a>beta <span class="ot">&lt;-</span> <span class="fu">solve</span>(<span class="fu">t</span>(X) <span class="sc">%*%</span> X) <span class="sc">%*%</span> <span class="fu">t</span>(X) <span class="sc">%*%</span> y</span>
<span id="cb27-2"><a href="regresión-múltiple.html#cb27-2" tabindex="-1"></a>beta</span></code></pre></div>
<pre><code>##            [,1]
## [1,] 2.34123115
## [2,] 1.61590721
## [3,] 0.01438483</code></pre>
</details>
<p>Entonces el ajuste por el método de mínimos cuadrados, con los coeficientes de regresión que encontramos está dado por:</p>
<p><span class="math inline">\(\hat{y} =\)</span> 2.3412311 <span class="math inline">\(+\)</span> 1.6159072 <span class="math inline">\(x_1\)</span> <span class="math inline">\(+\)</span> 1.6159072 <span class="math inline">\(x_2\)</span></p>
<p>Esto lo podemos hacer más rápido usando la función de <code>lm</code>. Construimos el modelo.</p>
<details>
<summary>
<b>Modelo en R</b>
</summary>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="regresión-múltiple.html#cb29-1" tabindex="-1"></a>M1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y <span class="sc">~</span> x1 <span class="sc">+</span> x2, datos)</span>
<span id="cb29-2"><a href="regresión-múltiple.html#cb29-2" tabindex="-1"></a>M1 </span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x1 + x2, data = datos)
## 
## Coefficients:
## (Intercept)           x1           x2  
##     2.34123      1.61591      0.01438</code></pre>
</details>
<p>¿Cómo accedemos a los valores del modelo?</p>
<details>
<summary>
<b>Coeficientes</b>
</summary>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="regresión-múltiple.html#cb31-1" tabindex="-1"></a>beta_0 <span class="ot">&lt;-</span> M1<span class="sc">$</span>coefficients[<span class="dv">1</span>]</span>
<span id="cb31-2"><a href="regresión-múltiple.html#cb31-2" tabindex="-1"></a>beta_1 <span class="ot">&lt;-</span> M1<span class="sc">$</span>coefficients[<span class="dv">2</span>]</span>
<span id="cb31-3"><a href="regresión-múltiple.html#cb31-3" tabindex="-1"></a>beta_2 <span class="ot">&lt;-</span> M1<span class="sc">$</span>coefficients[<span class="dv">3</span>]</span></code></pre></div>
</details>
<p>Los valores son <span class="math inline">\(\beta_0=\)</span> 2.3412311, <span class="math inline">\(\beta_1=\)</span> 1.6159072 y <span class="math inline">\(\beta_2=\)</span> 0.0143848.</p>
<ol start="2" style="list-style-type: decimal">
<li>Estimación de la varianza del error <span class="math inline">\(\sigma^2\)</span></li>
</ol>
<p>Ya tenemos que la suma de los cuadrados de los errores está dada por</p>
<p><span class="math display">\[ SSE = y&#39;y - \hat{\beta}X&#39;y\]</span></p>
<p>Sustituimos los valores que tenemos y obtemos el SSE.</p>
<details>
<summary>
<b>SSE</b>
</summary>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="regresión-múltiple.html#cb32-1" tabindex="-1"></a>SSE <span class="ot">&lt;-</span> <span class="fu">t</span>(y)<span class="sc">%*%</span> y <span class="sc">-</span> <span class="fu">t</span>(beta) <span class="sc">%*%</span> <span class="fu">t</span>(X) <span class="sc">%*%</span> y</span>
<span id="cb32-2"><a href="regresión-múltiple.html#cb32-2" tabindex="-1"></a>SSE</span></code></pre></div>
<pre><code>##          [,1]
## [1,] 233.7317</code></pre>
</details>
<p>Y de está forma, podemos encontrar el estimador de <span class="math inline">\(\sigma^2\)</span>.</p>
<details>
<summary>
<b>Estimador</b>
</summary>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="regresión-múltiple.html#cb34-1" tabindex="-1"></a>varest <span class="ot">&lt;-</span> SSE <span class="sc">/</span> (<span class="fu">nrow</span>(y) <span class="sc">-</span> <span class="fu">nrow</span>(beta))</span>
<span id="cb34-2"><a href="regresión-múltiple.html#cb34-2" tabindex="-1"></a>varest</span></code></pre></div>
<pre><code>##          [,1]
## [1,] 10.62417</code></pre>
</details>
<p>Directo con las funciones de R, podemos acceder a los parámetros que se guardaron en el modelo que ya calculamos.</p>
<details>
<summary>
<b>Resumen del modelo</b>
</summary>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="regresión-múltiple.html#cb36-1" tabindex="-1"></a><span class="fu">summary</span>(M1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x1 + x2, data = datos)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.7880 -0.6629  0.4364  1.1566  7.4197 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 2.341231   1.096730   2.135 0.044170 *  
## x1          1.615907   0.170735   9.464 3.25e-09 ***
## x2          0.014385   0.003613   3.981 0.000631 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.259 on 22 degrees of freedom
## Multiple R-squared:  0.9596, Adjusted R-squared:  0.9559 
## F-statistic: 261.2 on 2 and 22 DF,  p-value: 4.687e-16</code></pre>
</details>
<p>Algunos de los parámetros almacenados en el modelo nos permiten obtener también el resultado previo.</p>
<details>
<summary>
<b>Estimador</b>
</summary>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="regresión-múltiple.html#cb38-1" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">residuals</span>(M1)<span class="sc">^</span><span class="dv">2</span>) <span class="sc">/</span> <span class="fu">df.residual</span>(M1)</span></code></pre></div>
<pre><code>## [1] 10.62417</code></pre>
</details>
<div id="ejercicios" class="section level3 hasAnchor" number="2.3.1">
<h3><span class="header-section-number">2.3.1</span> Ejercicios<a href="regresión-múltiple.html#ejercicios" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>Ejercicio 1:</strong> Un analista hace un estudio químico y espera que el rendimiento de cierta sustancia se vea afectado por dos factores. Se realizan 17 experimentos cuyos datos se registran en el cuadro siguiente. Por experimentos similares, se sabe que los factores <span class="math inline">\(x_1\)</span> y <span class="math inline">\(x_2\)</span> no están relacionados; por ello, el analista decide utilizar un modelo de regresión lineal múltiple. Calcule el modelo de regresión y grafíquelo sobre las observaciones.</p>
<p><em>Archivo: est_quimico.csv</em></p>
<details>
<summary>
<b>Datos Ejercicio 1</b>
</summary>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="regresión-múltiple.html#cb40-1" tabindex="-1"></a>datos2 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb40-2"><a href="regresión-múltiple.html#cb40-2" tabindex="-1"></a>  <span class="at">Experimento =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">17</span>,</span>
<span id="cb40-3"><a href="regresión-múltiple.html#cb40-3" tabindex="-1"></a>  <span class="at">x1 =</span> <span class="fu">c</span>(<span class="fl">41.9</span>, <span class="fl">43.4</span>, <span class="fl">43.9</span>, <span class="fl">44.5</span>, <span class="fl">47.3</span>, <span class="fl">47.5</span>, <span class="fl">47.9</span>, <span class="fl">50.2</span>, <span class="fl">52.8</span>, <span class="fl">53.2</span>, <span class="fl">56.7</span>, <span class="fl">57.0</span>, <span class="fl">63.5</span>, <span class="fl">64.3</span>, <span class="fl">71.1</span>, <span class="fl">77.0</span>, <span class="fl">77.8</span>),</span>
<span id="cb40-4"><a href="regresión-múltiple.html#cb40-4" tabindex="-1"></a>  <span class="at">x2 =</span> <span class="fu">c</span>(<span class="fl">29.1</span>, <span class="fl">29.3</span>, <span class="fl">29.5</span>, <span class="fl">29.7</span>, <span class="fl">29.9</span>, <span class="fl">30.3</span>, <span class="fl">30.5</span>, <span class="fl">30.7</span>, <span class="fl">30.8</span>, <span class="fl">30.9</span>, <span class="fl">31.5</span>, <span class="fl">31.7</span>, <span class="fl">31.9</span>, <span class="fl">32.0</span>, <span class="fl">32.1</span>, <span class="fl">32.5</span>, <span class="fl">32.9</span>),</span>
<span id="cb40-5"><a href="regresión-múltiple.html#cb40-5" tabindex="-1"></a>  <span class="at">y  =</span> <span class="fu">c</span>(<span class="fl">251.3</span>, <span class="fl">251.3</span>, <span class="fl">248.3</span>, <span class="fl">267.5</span>, <span class="fl">273.0</span>, <span class="fl">276.5</span>, <span class="fl">270.3</span>, <span class="fl">274.9</span>, <span class="fl">285.0</span>, <span class="fl">290.0</span>, <span class="fl">297.0</span>, <span class="fl">302.5</span>, <span class="fl">304.5</span>, <span class="fl">309.3</span>, <span class="fl">321.7</span>, <span class="fl">330.7</span>, <span class="fl">349.0</span>)</span>
<span id="cb40-6"><a href="regresión-múltiple.html#cb40-6" tabindex="-1"></a>)</span>
<span id="cb40-7"><a href="regresión-múltiple.html#cb40-7" tabindex="-1"></a></span>
<span id="cb40-8"><a href="regresión-múltiple.html#cb40-8" tabindex="-1"></a>datos2</span></code></pre></div>
<pre><code>##    Experimento   x1   x2     y
## 1            1 41.9 29.1 251.3
## 2            2 43.4 29.3 251.3
## 3            3 43.9 29.5 248.3
## 4            4 44.5 29.7 267.5
## 5            5 47.3 29.9 273.0
## 6            6 47.5 30.3 276.5
## 7            7 47.9 30.5 270.3
## 8            8 50.2 30.7 274.9
## 9            9 52.8 30.8 285.0
## 10          10 53.2 30.9 290.0
## 11          11 56.7 31.5 297.0
## 12          12 57.0 31.7 302.5
## 13          13 63.5 31.9 304.5
## 14          14 64.3 32.0 309.3
## 15          15 71.1 32.1 321.7
## 16          16 77.0 32.5 330.7
## 17          17 77.8 32.9 349.0</code></pre>
</details>
<p><strong>Ejercicio 2:</strong> Repetir el ejemplo con los datos <code>datasets::trees</code> de R que proporciona mediciones
del diámetro, altura y volumen de madera en 31 cerezos negros talados.</p>
<p><strong>Ejercicio 3:</strong> Subir a Github los dos ejercicios previos tanto con solución en R como en Python. Comparar las funciones. Ventajas y desventajas de ambas.</p>
</div>
</div>
<div id="pruebas-de-hipótesis" class="section level2 hasAnchor" number="2.4">
<h2><span class="header-section-number">2.4</span> Pruebas de Hipótesis<a href="#pruebas-de-hip%C3%B3tesis" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Cuando revisamos el <code>summary</code> del modelo, nos arroja si son significativas o no y a que nivel de significancia las variables que estamos considerando. Veamos el siguiente ejemplo.</p>
<div id="prueba-de-la-significancia-de-la-regresión" class="section level3 hasAnchor" number="2.4.1">
<h3><span class="header-section-number">2.4.1</span> Prueba de la significancia de la regresión<a href="#prueba-de-la-significancia-de-la-regresi%C3%B3n" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>Ejemplo:</strong> Con los datos del embotellador de bebidas gaseosas, se probará la significancia de la regresión.</p>
<details>
<summary>
<b>Sumas de Cuadrados</b>
</summary>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="regresión-múltiple.html#cb42-1" tabindex="-1"></a>SCT <span class="ot">&lt;-</span> <span class="fu">t</span>(y) <span class="sc">%*%</span> y <span class="sc">-</span>  <span class="fu">sum</span>(y)<span class="sc">**</span><span class="dv">2</span> <span class="sc">/</span> <span class="fu">nrow</span>(datos)</span>
<span id="cb42-2"><a href="regresión-múltiple.html#cb42-2" tabindex="-1"></a>SCT</span></code></pre></div>
<pre><code>##          [,1]
## [1,] 5784.543</code></pre>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="regresión-múltiple.html#cb44-1" tabindex="-1"></a>SCE <span class="ot">&lt;-</span> <span class="fu">t</span>(beta) <span class="sc">%*%</span> <span class="fu">t</span>(X) <span class="sc">%*%</span> y <span class="sc">-</span> <span class="fu">sum</span>(y)<span class="sc">**</span><span class="dv">2</span> <span class="sc">/</span> <span class="fu">nrow</span>(datos)</span>
<span id="cb44-2"><a href="regresión-múltiple.html#cb44-2" tabindex="-1"></a>SCE</span></code></pre></div>
<pre><code>##          [,1]
## [1,] 5550.811</code></pre>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="regresión-múltiple.html#cb46-1" tabindex="-1"></a>SSE <span class="ot">&lt;-</span> SCT <span class="sc">-</span> SCE</span>
<span id="cb46-2"><a href="regresión-múltiple.html#cb46-2" tabindex="-1"></a>SSE</span></code></pre></div>
<pre><code>##          [,1]
## [1,] 233.7317</code></pre>
</details>
<p>Para probar</p>
<p><span class="math display">\[H_0 : \beta_1 = \beta_2=0\]</span></p>
<p>se calcula el estadístico:</p>
<details>
<summary>
<b>Estadístico F</b>
</summary>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="regresión-múltiple.html#cb48-1" tabindex="-1"></a>F0 <span class="ot">&lt;-</span> (SCE <span class="sc">/</span> (<span class="fu">ncol</span>(X) <span class="sc">-</span> <span class="dv">1</span>)) <span class="sc">/</span> (SSE <span class="sc">/</span> (<span class="fu">nrow</span>(X) <span class="sc">-</span> (<span class="fu">ncol</span>(X) <span class="sc">-</span><span class="dv">1</span>) <span class="sc">-</span> <span class="dv">1</span>))</span>
<span id="cb48-2"><a href="regresión-múltiple.html#cb48-2" tabindex="-1"></a>F0</span></code></pre></div>
<pre><code>##          [,1]
## [1,] 261.2351</code></pre>
</details>
<p>Como el valor de <span class="math inline">\(F_0\)</span> es mayor que el valor tabulado de <span class="math inline">\(F_{\alpha;p,n-p-1}=F_{0.05;2;22}=3.44\)</span>, se rechaza <span class="math inline">\(H_0\)</span>. Lo cual implica qye el tiempo de entrega depende del volumen de entrega y/o de la distancia.</p>
<p>Ahora, usando los modelos que ya calculamos.</p>
<details>
<summary>
<b>Sumas de cuadrados</b>
</summary>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="regresión-múltiple.html#cb50-1" tabindex="-1"></a>SCT.m<span class="ot">&lt;-</span><span class="fu">sum</span>((datos<span class="sc">$</span>y<span class="sc">-</span><span class="fu">mean</span>(datos<span class="sc">$</span>y))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb50-2"><a href="regresión-múltiple.html#cb50-2" tabindex="-1"></a>SCT.m</span></code></pre></div>
<pre><code>## [1] 5784.543</code></pre>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="regresión-múltiple.html#cb52-1" tabindex="-1"></a>SCE.m <span class="ot">&lt;-</span><span class="fu">sum</span>((M1<span class="sc">$</span>fitted<span class="sc">-</span><span class="fu">mean</span>(datos<span class="sc">$</span>y))<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb52-2"><a href="regresión-múltiple.html#cb52-2" tabindex="-1"></a>SCE.m</span></code></pre></div>
<pre><code>## [1] 5550.811</code></pre>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="regresión-múltiple.html#cb54-1" tabindex="-1"></a>SSE.m <span class="ot">&lt;-</span><span class="fu">sum</span>(M1<span class="sc">$</span>residuals<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb54-2"><a href="regresión-múltiple.html#cb54-2" tabindex="-1"></a>SSE.m</span></code></pre></div>
<pre><code>## [1] 233.7317</code></pre>
</details>
<details>
<summary>
<b>Grados de libertad</b>
</summary>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="regresión-múltiple.html#cb56-1" tabindex="-1"></a>n<span class="ot">&lt;-</span><span class="fu">nrow</span>(y)</span>
<span id="cb56-2"><a href="regresión-múltiple.html#cb56-2" tabindex="-1"></a>n</span></code></pre></div>
<pre><code>## [1] 25</code></pre>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="regresión-múltiple.html#cb58-1" tabindex="-1"></a>GLT<span class="ot">&lt;-</span> n<span class="dv">-1</span></span>
<span id="cb58-2"><a href="regresión-múltiple.html#cb58-2" tabindex="-1"></a>GLT</span></code></pre></div>
<pre><code>## [1] 24</code></pre>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="regresión-múltiple.html#cb60-1" tabindex="-1"></a>GLRes<span class="ot">&lt;-</span> <span class="fu">df.residual</span>(M1)</span>
<span id="cb60-2"><a href="regresión-múltiple.html#cb60-2" tabindex="-1"></a>GLRes</span></code></pre></div>
<pre><code>## [1] 22</code></pre>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="regresión-múltiple.html#cb62-1" tabindex="-1"></a>GLR<span class="ot">&lt;-</span> GLT<span class="sc">-</span>GLRes</span>
<span id="cb62-2"><a href="regresión-múltiple.html#cb62-2" tabindex="-1"></a>GLR</span></code></pre></div>
<pre><code>## [1] 2</code></pre>
</details>
<details>
<summary>
<b>Cuadrados medios</b>
</summary>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="regresión-múltiple.html#cb64-1" tabindex="-1"></a>CMR <span class="ot">&lt;-</span> SCE <span class="sc">/</span>GLR</span>
<span id="cb64-2"><a href="regresión-múltiple.html#cb64-2" tabindex="-1"></a>CMR</span></code></pre></div>
<pre><code>##          [,1]
## [1,] 2775.405</code></pre>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="regresión-múltiple.html#cb66-1" tabindex="-1"></a>CMRes <span class="ot">&lt;-</span> SSE <span class="sc">/</span> GLRes</span>
<span id="cb66-2"><a href="regresión-múltiple.html#cb66-2" tabindex="-1"></a>CMRes</span></code></pre></div>
<pre><code>##          [,1]
## [1,] 10.62417</code></pre>
</details>
<details>
<summary>
<b>Estadístico F_0</b>
</summary>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="regresión-múltiple.html#cb68-1" tabindex="-1"></a>F0 <span class="ot">&lt;-</span> CMR<span class="sc">/</span>CMRes</span>
<span id="cb68-2"><a href="regresión-múltiple.html#cb68-2" tabindex="-1"></a>F0</span></code></pre></div>
<pre><code>##          [,1]
## [1,] 261.2351</code></pre>
</details>
<details>
<summary>
<b>p-valor</b>
</summary>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="regresión-múltiple.html#cb70-1" tabindex="-1"></a>pv <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">-</span> <span class="fu">pf</span>(F0, GLR,GLRes)</span>
<span id="cb70-2"><a href="regresión-múltiple.html#cb70-2" tabindex="-1"></a>pv</span></code></pre></div>
<pre><code>##              [,1]
## [1,] 4.440892e-16</code></pre>
</details>
<details>
<summary>
<b>Valor tabulado de F</b>
</summary>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="regresión-múltiple.html#cb72-1" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span>; df1 <span class="ot">&lt;-</span> <span class="dv">2</span>; df2 <span class="ot">&lt;-</span> <span class="dv">22</span></span>
<span id="cb72-2"><a href="regresión-múltiple.html#cb72-2" tabindex="-1"></a>F_crit <span class="ot">&lt;-</span> <span class="fu">qf</span>(<span class="dv">1</span> <span class="sc">-</span> alpha, df1, df2)</span>
<span id="cb72-3"><a href="regresión-múltiple.html#cb72-3" tabindex="-1"></a>F_crit</span></code></pre></div>
<pre><code>## [1] 3.443357</code></pre>
</details>
</div>
<div id="pruebas-sobre-coeficientes-individuales-de-regresión" class="section level3 hasAnchor" number="2.4.2">
<h3><span class="header-section-number">2.4.2</span> Pruebas sobre coeficientes individuales de regresión<a href="#pruebas-sobre-coeficientes-individuales-de-regresi%C3%B3n" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>Ejemplo:</strong> Usando los datos del embotellador de bebidas gaseosas, se desea evaluar la importancia de la variable regresora <em>distancia</em> (<span class="math inline">\(x_2\)</span>) dado que el regresor <em>cajas</em> (<span class="math inline">\(x_1\)</span>) está en el modelo.</p>
<details>
<summary>
<b>Estadístico t_0</b>
</summary>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="regresión-múltiple.html#cb74-1" tabindex="-1"></a>C22 <span class="ot">&lt;-</span> <span class="fu">solve</span>(<span class="fu">t</span>(X) <span class="sc">%*%</span> X)[<span class="dv">3</span>,<span class="dv">3</span>]</span>
<span id="cb74-2"><a href="regresión-múltiple.html#cb74-2" tabindex="-1"></a>C22</span></code></pre></div>
<pre><code>## [1] 1.228745e-06</code></pre>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="regresión-múltiple.html#cb76-1" tabindex="-1"></a>t0 <span class="ot">&lt;-</span> beta_2 <span class="sc">/</span> <span class="fu">sqrt</span>(varest <span class="sc">*</span> C22)</span>
<span id="cb76-2"><a href="regresión-múltiple.html#cb76-2" tabindex="-1"></a>t0</span></code></pre></div>
<pre><code>##          [,1]
## [1,] 3.981313</code></pre>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="regresión-múltiple.html#cb78-1" tabindex="-1"></a><span class="do">## t tabulado con confianza 95% y 22 grados de libertad</span></span>
<span id="cb78-2"><a href="regresión-múltiple.html#cb78-2" tabindex="-1"></a>tt <span class="ot">&lt;-</span> <span class="fu">qt</span>(<span class="at">p =</span> <span class="fl">0.95</span> <span class="sc">+</span> <span class="fl">0.05</span><span class="sc">/</span><span class="dv">2</span>, <span class="at">df =</span> <span class="dv">22</span>, <span class="at">lower.tail =</span> <span class="cn">TRUE</span>)</span>
<span id="cb78-3"><a href="regresión-múltiple.html#cb78-3" tabindex="-1"></a>tt</span></code></pre></div>
<pre><code>## [1] 2.073873</code></pre>
</details>
<p>Usando el modelo que ya tenemos calculado <code>M1</code> podemos obtener estos mismos resultados de la siguiente forma.</p>
<details>
<summary>
<b>Prueba sobre coeficientes</b>
</summary>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="regresión-múltiple.html#cb80-1" tabindex="-1"></a><span class="fu">summary</span>(M1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y ~ x1 + x2, data = datos)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -5.7880 -0.6629  0.4364  1.1566  7.4197 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 2.341231   1.096730   2.135 0.044170 *  
## x1          1.615907   0.170735   9.464 3.25e-09 ***
## x2          0.014385   0.003613   3.981 0.000631 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.259 on 22 degrees of freedom
## Multiple R-squared:  0.9596, Adjusted R-squared:  0.9559 
## F-statistic: 261.2 on 2 and 22 DF,  p-value: 4.687e-16</code></pre>
</details>
</div>
</div>
<div id="intervalos-de-confianza" class="section level2 hasAnchor" number="2.5">
<h2><span class="header-section-number">2.5</span> Intervalos de confianza<a href="regresión-múltiple.html#intervalos-de-confianza" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>Ejemplo:</strong> Usando los datos del embotellador de bebidas gaseosas, queremos calcular el intervalo de confianza del 95% para <span class="math inline">\(\beta_1\)</span>. Recordemos que el estimador puntual de <span class="math inline">\(\beta_1\)</span> es 1.6159072.</p>
<details>
<summary>
<b>Intervalo de confianza</b>
</summary>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="regresión-múltiple.html#cb82-1" tabindex="-1"></a>C11 <span class="ot">&lt;-</span> <span class="fu">solve</span>(<span class="fu">t</span>(X) <span class="sc">%*%</span> X)[<span class="dv">2</span>,<span class="dv">2</span>]</span>
<span id="cb82-2"><a href="regresión-múltiple.html#cb82-2" tabindex="-1"></a></span>
<span id="cb82-3"><a href="regresión-múltiple.html#cb82-3" tabindex="-1"></a>izq <span class="ot">&lt;-</span> beta_1 <span class="sc">-</span> tt <span class="sc">*</span> <span class="fu">sqrt</span>(varest<span class="sc">*</span>C11)</span>
<span id="cb82-4"><a href="regresión-múltiple.html#cb82-4" tabindex="-1"></a>izq</span></code></pre></div>
<pre><code>##          [,1]
## [1,] 1.261825</code></pre>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="regresión-múltiple.html#cb84-1" tabindex="-1"></a>der <span class="ot">&lt;-</span> beta_1 <span class="sc">+</span> tt <span class="sc">*</span> <span class="fu">sqrt</span>(varest<span class="sc">*</span>C11)</span>
<span id="cb84-2"><a href="regresión-múltiple.html#cb84-2" tabindex="-1"></a>der</span></code></pre></div>
<pre><code>##         [,1]
## [1,] 1.96999</code></pre>
</details>
<div id="intervalo-de-confianza-de-la-respuesta-media" class="section level3 hasAnchor" number="2.5.1">
<h3><span class="header-section-number">2.5.1</span> Intervalo de confianza de la respuesta media<a href="regresión-múltiple.html#intervalo-de-confianza-de-la-respuesta-media" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><strong>Ejemplo:</strong> El embotellador de bebidas gaseosas quiere establecer un intervalo de confianza del 95% para el tiempo medio de entrega para una tienda donde se requieren <span class="math inline">\(x_1=8\)</span> cajas y la distancia es de <span class="math inline">\(x_2=275\)</span> pies.</p>
Nuestro vector <span class="math inline">\(X_0\)</span> está dado por:
<details>
<summary>
<b>X0</b>
</summary>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="regresión-múltiple.html#cb86-1" tabindex="-1"></a>X0 <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">8</span>, <span class="dv">275</span>), <span class="at">nrow =</span> <span class="dv">3</span>)</span>
<span id="cb86-2"><a href="regresión-múltiple.html#cb86-2" tabindex="-1"></a>X0</span></code></pre></div>
<pre><code>##      [,1]
## [1,]    1
## [2,]    8
## [3,]  275</code></pre>
</details>
<p>El valor ajustado en ese punto es:</p>
<details>
<summary>
<b>Valor ajustado</b>
</summary>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="regresión-múltiple.html#cb88-1" tabindex="-1"></a>y0 <span class="ot">&lt;-</span> <span class="fu">t</span>(X0) <span class="sc">%*%</span> beta</span>
<span id="cb88-2"><a href="regresión-múltiple.html#cb88-2" tabindex="-1"></a>y0</span></code></pre></div>
<pre><code>##          [,1]
## [1,] 19.22432</code></pre>
</details>
<p>La varianza de <span class="math inline">\(\hat{y_0}\)</span></p>
<details>
<summary>
<b>Varianza</b>
</summary>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="regresión-múltiple.html#cb90-1" tabindex="-1"></a>var_y0 <span class="ot">&lt;-</span> varest <span class="sc">*</span> <span class="fu">t</span>(X0) <span class="sc">%*%</span> <span class="fu">solve</span>(<span class="fu">t</span>(X) <span class="sc">%*%</span> X) <span class="sc">%*%</span> X0</span>
<span id="cb90-2"><a href="regresión-múltiple.html#cb90-2" tabindex="-1"></a>var_y0</span></code></pre></div>
<pre><code>##           [,1]
## [1,] 0.5734134</code></pre>
</details>
<p>Entonces el intervalo de confianza en este punto es:</p>
<details>
<summary>
<b>Intervalo de confianza</b>
</summary>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="regresión-múltiple.html#cb92-1" tabindex="-1"></a>l_izq <span class="ot">&lt;-</span> y0 <span class="sc">-</span> tt <span class="sc">*</span> <span class="fu">sqrt</span>(var_y0) </span>
<span id="cb92-2"><a href="regresión-múltiple.html#cb92-2" tabindex="-1"></a>l_izq</span></code></pre></div>
<pre><code>##         [,1]
## [1,] 17.6539</code></pre>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="regresión-múltiple.html#cb94-1" tabindex="-1"></a>l_der <span class="ot">&lt;-</span> y0 <span class="sc">+</span> tt <span class="sc">*</span> <span class="fu">sqrt</span>(var_y0) </span>
<span id="cb94-2"><a href="regresión-múltiple.html#cb94-2" tabindex="-1"></a>l_der</span></code></pre></div>
<pre><code>##          [,1]
## [1,] 20.79474</code></pre>
</details>
<p><strong>Ejemplo: </strong> Usaremos el conjunto de datos <code>data("marketing")</code> que contiene 200 observaciones de un experimento publicitario que evalúa el impacto de tres medios de anuncio en las ventas. Para cada observación se registran los presupuestos de publicidad (en miles de dólares) y las ventas obtenidas.
Variables:</p>
<ul>
<li><code>youtube</code>: presupuesto invertido en anuncios de YouTube (miles de USD).</li>
<li><code>facebook</code>: presupuesto invertido en Facebook (miles de USD).</li>
<li><code>newspaper</code>: presupuesto invertido en prensa escrita (miles de USD).</li>
<li><code>sales</code>: ventas registradas (variable respuesta).</li>
</ul>
<p>Cargamos los datos:</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="regresión-múltiple.html#cb96-1" tabindex="-1"></a><span class="fu">library</span>(datarium)</span>
<span id="cb96-2"><a href="regresión-múltiple.html#cb96-2" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;marketing&quot;</span>)</span></code></pre></div>
<p>Exploramos rápidamente la base para ver qué variables contiene y la dimensión:</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="regresión-múltiple.html#cb97-1" tabindex="-1"></a><span class="fu">str</span>(marketing)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    200 obs. of  4 variables:
##  $ youtube  : num  276.1 53.4 20.6 181.8 217 ...
##  $ facebook : num  45.4 47.2 55.1 49.6 13 ...
##  $ newspaper: num  83 54.1 83.2 70.2 70.1 ...
##  $ sales    : num  26.5 12.5 11.2 22.2 15.5 ...</code></pre>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="regresión-múltiple.html#cb99-1" tabindex="-1"></a><span class="co">#?marketing</span></span></code></pre></div>
<p>Ajustamos un modelo lineal que incluya todas las variables, es decir,</p>
<p><span class="math inline">\(sales=\beta_0+\beta_1 youtube+\beta_2 facebook+ \beta_3 newspaper+\epsilon\)</span></p>
<details>
<summary>
<b>Modelo marketing</b>
</summary>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="regresión-múltiple.html#cb100-1" tabindex="-1"></a>modelo1<span class="ot">&lt;-</span><span class="fu">lm</span>(sales<span class="sc">~</span>youtube<span class="sc">+</span>facebook<span class="sc">+</span>newspaper,<span class="at">data=</span>marketing)</span>
<span id="cb100-2"><a href="regresión-múltiple.html#cb100-2" tabindex="-1"></a><span class="fu">summary</span>(modelo1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = sales ~ youtube + facebook + newspaper, data = marketing)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -10.5932  -1.0690   0.2902   1.4272   3.3951 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  3.526667   0.374290   9.422   &lt;2e-16 ***
## youtube      0.045765   0.001395  32.809   &lt;2e-16 ***
## facebook     0.188530   0.008611  21.893   &lt;2e-16 ***
## newspaper   -0.001037   0.005871  -0.177     0.86    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.023 on 196 degrees of freedom
## Multiple R-squared:  0.8972, Adjusted R-squared:  0.8956 
## F-statistic: 570.3 on 3 and 196 DF,  p-value: &lt; 2.2e-16</code></pre>
</details>
<p>¿Qué se puede decir sobre la significancia de la variable <span class="math inline">\(newspaper\)</span>?</p>
<p>Veamos qué ocurre con el modelo al eliminar la variable <span class="math inline">\(newspaper\)</span></p>
<details>
<summary>
<b>Modelo marketing 2</b>
</summary>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="regresión-múltiple.html#cb102-1" tabindex="-1"></a>modelo2<span class="ot">&lt;-</span><span class="fu">lm</span>(sales<span class="sc">~</span>facebook<span class="sc">+</span>youtube,<span class="at">data=</span>marketing)</span>
<span id="cb102-2"><a href="regresión-múltiple.html#cb102-2" tabindex="-1"></a><span class="fu">summary</span>(modelo2)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = sales ~ facebook + youtube, data = marketing)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -10.5572  -1.0502   0.2906   1.4049   3.3994 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  3.50532    0.35339   9.919   &lt;2e-16 ***
## facebook     0.18799    0.00804  23.382   &lt;2e-16 ***
## youtube      0.04575    0.00139  32.909   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.018 on 197 degrees of freedom
## Multiple R-squared:  0.8972, Adjusted R-squared:  0.8962 
## F-statistic: 859.6 on 2 and 197 DF,  p-value: &lt; 2.2e-16</code></pre>
</details>
<p>Lo que sigue, es hacer pruebas de hipótesis tanto en las variables como en los coeficientes de regresión.</p>
<p><strong>Ejercicio 1:</strong> Realizar las pruebas de hipótesis sobre la significancia de la regresión y sobre los coeficientes. Encontrar los intervalos de confianza respectivos del 95%.
Para una tienda con presupuestos:
<span class="math inline">\(youtube = 150\)</span>, <span class="math inline">\(facebook = 30\)</span>, <span class="math inline">\(newspaper=20\)</span> (en miles de USD):
(a) Calcula el intervalo de confianza del 95% para la media de ventas <span class="math inline">\(\mathbb{E}(sales | X_0)\)</span>.
(b) Calcula el intervalo de predicción del 95% para una nueva observación de ventas.
(c) Comenta la diferencia entre ambos intervalos.
Subir respuesta y explicación de sus resultados a github.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="análisis-de-componentes-principales.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/HaydeePeruyero/MultivariateStatisticalAnalysis/edit/main/01-Regresion_multiple.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["MultivariateStatisticalAnalysis.pdf", "MultivariateStatisticalAnalysis.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  },
  "code_folding": "hide"
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
